name: Build + Push to Docker Hub workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  auth:
    name: Auth
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '14.18.1'

      - name: Install dependencies
        run: |
          cd ./src/auth
          npm ci

      - name: Unit test
        run: |
          cd ./src/auth
          npm run test

  room:
    name: Room
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '14.18.1'

      - name: Install dependencies
        run: |
          cd ./src/room
          npm ci

      - name: Unit test
        run: |
          cd ./src/room
          npm run test

  chat:
    name: Chat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '14.18.1'

      - name: Install dependencies
        run: |
          cd ./src/chat
          npm ci

      - name: Unit test
        run: |
          cd ./src/chat
          npm run test

  statistic:
    name: Statistic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '14.18.1'

      - name: Install dependencies
        run: |
          cd ./src/statistic
          npm ci

      - name: Unit test
        run: |
          cd ./src/statistic
          npm run test

  build_push:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Gateway
        uses: docker/build-push-action@v2
        with:
          context: ./gateway
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/CW-gateway:v1.0

      - name: Build and Push Auth
        uses: docker/build-push-action@v2
        with:
          context: ./auth
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/CW-auth:v1.0

      - name: Build and Push Room
        uses: docker/build-push-action@v2
        with:
          context: ./room
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/CW-room:v1.0

      - name: Build and Push Chat
        uses: docker/build-push-action@v2
        with:
          context: ./chat
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/CW-chat:v1.0

      - name: Build and Push Statistic
        uses: docker/build-push-action@v2
        with:
          context: ./statistic
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/CW-statistic:v1.0

      - name: Build and Push Frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/CW-frontend:v1.0
